project: mitotic_classifier

model_params:
  name: 'resnet'
  depth: 50
  in_channels: 2
  num_classes: 9
  class_weight: [1, 1, 1, 1, 1, 1, 1, 1, 1]
  trained_model: 
    - model: 'cell_classifier_dev_ensemble1' #v1
    - model: 'cell_classifier_dev_ensemble2' #v2
    - model: 'cell_classifier_dev_ensemble3' #v1

test_data:
  mode: folder
  #data_type: 'preprocessed_npy'
  data_path: ''
  runtime_aug: 1
  num_worker: 8
  batch_size: 32
  annotated: True
  output_path: ''

exp_params:
  # seed
  manual_seed: 1265
  # data parameters
  dataloader: 
    name: 'AdaptivePaddingBatch'
    num_worker: 4
    batch_size: 12
    shape: [100, 200, 200]
  training_data_path: ""
  validation_data_path: "3"
  # hyper parameters
  LR: 0.001
  weight_decay: 0.0005
  scheduler: 
    name: 'ExponentialLR' 
    gamma: 0.95
    # name: CosineAnnealingLR 
    # T_max: 10

trainer_params:
  precision: 16
  gpus: 1
  # distributed_backend: 'ddp'
  # num_nodes: 1
  max_epochs: 500
  accumulate_grad_batches: 2
  gradient_clip_val: 0.5

logging_params:
  save_dir: "logs/full/"
  