project: mitotic_classifier

model_params:
  name: 'resnet'
  depth: 50
  in_channels: 2
  num_classes: 9
  class_weight: [1, 1, 1, 1, 1, 1, 1, 1, 1]
  trained_model: 
    - model: 'cell_classifier_dev_ensemble1' #v1
    - model: 'cell_classifier_dev_ensemble2' #v2
    - model: 'cell_classifier_dev_ensemble3' #v1

test_data_loader:
  name: 'AdaptivePaddingBatch'
  mode: df
  data_path: ''
  runtime_aug: 1
  num_worker: 8
  batch_size: 32
  annotated: True
  shape: [100, 200, 200]

trainer_params:
  precision: 16
  gpus: 1
  logger: False
  distributed_backend: 'ddp'
  num_nodes: 1
  