project: mitotic_classifier

model_params:
  name: 'resnet'
  depth: 50
  in_channels: 2
  num_classes: 9
  trained_model: # may add multiple models
    - model: "/path/to/model_1"
    - model: "/path/to/model_2"

test_data_loader:
  name: 'AdaptivePaddingBatch'
  mode: folder
  data_path: ''
  runtime_aug: 1
  num_worker: 8
  batch_size: 32
  annotated: True
  shape: [100, 200, 200]

trainer_params:
  precision: 16
  gpus: 2
  logger: False
  distributed_backend: 'ddp'
  num_nodes: 1
